-- ===========================================================================
-- 0001 — foundation: extensions, shared helpers, platform configuration,
--        the service catalogue, the aviation registry and the aircraft fleet.
--
-- Conventions used throughout every Apron migration:
--   * primary keys are uuid, generated by the database;
--   * instants are timestamptz (UTC); local wall times are never stored;
--   * every status column is text + CHECK rather than a Postgres enum, because
--     ALTER TYPE ... ADD VALUE cannot run inside the transaction this runner
--     wraps each migration in (ADR-003);
--   * `service_category` is deliberately NOT an enum anywhere (ADR-008);
--   * every table that a UI orders by has a supporting index.
-- ===========================================================================

create extension if not exists "pgcrypto";    -- gen_random_uuid()
create extension if not exists "btree_gist";  -- exclusion constraints over scalars + ranges
create extension if not exists "pg_trgm";     -- fuzzy search over names (CLAUDE.md §15)
create extension if not exists "citext";      -- case-insensitive email identity

-- ---------------------------------------------------------------------------
-- updated_at maintenance. Applied by trigger rather than by application code so
-- a direct SQL fix or a background job cannot leave a stale timestamp behind.
-- ---------------------------------------------------------------------------
create or replace function apron_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Weekday-based recurring hours are modelled identically everywhere they occur
-- (FBO desks, provider coverage desks, driver shifts, officer shifts).
--
--   weekday      ISO 8601: 1 = Monday .. 7 = Sunday, interpreted in the owning
--                record's IANA zone.
--   open_minute  minutes from local midnight, 0..1439.
--   close_minute minutes from local midnight, 1..2880. Values above 1440 cross
--                midnight into the following day — a Friday 18:00 -> Saturday
--                02:00 desk is (weekday 5, 1080, 1560).
--
-- This matches `src/lib/time/hours.ts` exactly; the boundary is tested.
-- ---------------------------------------------------------------------------
create domain apron_weekday as smallint
  check (value between 1 and 7);

create domain apron_open_minute as integer
  check (value between 0 and 1439);

create domain apron_close_minute as integer
  check (value between 1 and 2880);

-- ---------------------------------------------------------------------------
-- Platform configuration
-- ---------------------------------------------------------------------------
create table platform_settings (
  key          text        primary key,
  value        jsonb       not null,
  description  text        not null default '',
  updated_by   uuid,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create trigger platform_settings_touch
  before update on platform_settings
  for each row execute function apron_touch_updated_at();

create table feature_flags (
  key          text        primary key,
  enabled      boolean     not null default false,
  description  text        not null default '',
  updated_by   uuid,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create trigger feature_flags_touch
  before update on feature_flags
  for each row execute function apron_touch_updated_at();

-- ---------------------------------------------------------------------------
-- Service catalogue (ADR-008)
--
-- `assignment_strategy` selects which concrete-resource rules the eligibility
-- engine applies. A category created by an admin with a strategy of 'generic'
-- is matched on coverage, desk hours, lead time and capacity alone — which is
-- why a new service works with no migration and no code change.
-- ---------------------------------------------------------------------------
create table service_categories (
  id                  uuid        primary key default gen_random_uuid(),
  code                text        not null,
  name                text        not null,
  description         text        not null default '',
  unit_label          text        not null,
  assignment_strategy text        not null default 'generic',
  config_schema_json  jsonb       not null default '{"fields":[]}'::jsonb,
  sort_order          integer     not null default 100,
  active              boolean     not null default true,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  constraint service_categories_code_format
    check (code ~ '^[a-z][a-z0-9_]{1,48}$'),
  constraint service_categories_strategy_known
    check (assignment_strategy in (
      'generic', 'vehicle_with_driver', 'officer', 'hotel_rooms',
      'catering_order', 'fuel_uplift', 'hangar_slot'
    ))
);

create unique index service_categories_code_key on service_categories (code);
create index service_categories_active_order_idx
  on service_categories (active, sort_order, name);

create trigger service_categories_touch
  before update on service_categories
  for each row execute function apron_touch_updated_at();

-- ---------------------------------------------------------------------------
-- Airports
--
-- ICAO and IATA are unique *where present* (CLAUDE.md §6). Coordinates are
-- numeric, never float, so a stored position round-trips exactly.
-- ---------------------------------------------------------------------------
create table airports (
  id             uuid          primary key default gen_random_uuid(),
  icao           text,
  iata           text,
  name           text          not null,
  city           text          not null,
  state_region   text,
  country_code   text          not null,
  latitude       numeric(9,6)  not null,
  longitude      numeric(9,6)  not null,
  timezone_iana  text          not null,
  active         boolean       not null default true,
  created_at     timestamptz   not null default now(),
  updated_at     timestamptz   not null default now(),

  constraint airports_identifier_present     check (icao is not null or iata is not null),
  constraint airports_icao_format            check (icao is null or icao ~ '^[A-Z0-9]{4}$'),
  constraint airports_iata_format            check (iata is null or iata ~ '^[A-Z]{3}$'),
  constraint airports_country_format         check (country_code ~ '^[A-Z]{2}$'),
  constraint airports_latitude_range         check (latitude between -90 and 90),
  constraint airports_longitude_range        check (longitude between -180 and 180),
  constraint airports_timezone_present       check (length(timezone_iana) > 0)
);

create unique index airports_icao_key on airports (icao) where icao is not null;
create unique index airports_iata_key on airports (iata) where iata is not null;
create index airports_name_trgm_idx on airports using gin (name gin_trgm_ops);
create index airports_city_trgm_idx on airports using gin (city gin_trgm_ops);
create index airports_active_name_idx on airports (active, name, id);

create trigger airports_touch
  before update on airports
  for each row execute function apron_touch_updated_at();

-- ---------------------------------------------------------------------------
-- FBOs. An airport may have several; a request may name one or none.
-- ---------------------------------------------------------------------------
create table fbos (
  id          uuid          primary key default gen_random_uuid(),
  airport_id  uuid          not null references airports (id) on delete restrict,
  name        text          not null,
  phone       text,
  email       citext,
  address     text,
  website     text,
  latitude    numeric(9,6),
  longitude   numeric(9,6),
  active      boolean       not null default true,
  created_at  timestamptz   not null default now(),
  updated_at  timestamptz   not null default now(),

  constraint fbos_latitude_range  check (latitude  is null or latitude  between  -90 and  90),
  constraint fbos_longitude_range check (longitude is null or longitude between -180 and 180),
  -- Coordinates are stored as a pair or not at all; half a position is useless
  -- and would render a marker in the wrong place (CLAUDE.md §17).
  constraint fbos_coordinates_paired
    check ((latitude is null) = (longitude is null))
);

create unique index fbos_airport_name_key on fbos (airport_id, lower(name));
create index fbos_airport_idx on fbos (airport_id, name, id);
create index fbos_name_trgm_idx on fbos using gin (name gin_trgm_ops);

create trigger fbos_touch
  before update on fbos
  for each row execute function apron_touch_updated_at();

-- FBO desk hours, in the parent airport's zone.
create table fbo_operating_hours (
  id            uuid                primary key default gen_random_uuid(),
  fbo_id        uuid                not null references fbos (id) on delete cascade,
  weekday       apron_weekday       not null,
  open_minute   apron_open_minute   not null,
  close_minute  apron_close_minute  not null,

  constraint fbo_hours_ordered check (close_minute > open_minute)
);

create index fbo_operating_hours_fbo_idx on fbo_operating_hours (fbo_id, weekday, open_minute);

-- ---------------------------------------------------------------------------
-- Aircraft
--
-- Dimensions are the inputs the hangar eligibility rule needs; they are stored
-- as numerics and are nullable, because an unknown wingspan must make a hangar
-- check *fail loudly* rather than silently pass on a default.
-- ---------------------------------------------------------------------------
create table aircraft (
  id                   uuid          primary key default gen_random_uuid(),
  tail_number          text          not null,
  type_code            text,
  model                text          not null,
  manufacturer         text,
  operator_name        text,
  category             text          not null default 'midsize',
  passenger_capacity   integer,
  wingspan_ft          numeric(6,2),
  length_ft            numeric(6,2),
  tail_height_ft       numeric(6,2),
  mtow_lbs             integer,
  notes                text          not null default '',
  active               boolean       not null default true,
  created_at           timestamptz   not null default now(),
  updated_at           timestamptz   not null default now(),

  constraint aircraft_tail_format
    check (tail_number ~ '^[A-Z0-9-]{2,12}$'),
  constraint aircraft_category_known
    check (category in ('very_light', 'light', 'midsize', 'super_midsize', 'heavy', 'ultra_long_range', 'airliner')),
  constraint aircraft_capacity_positive
    check (passenger_capacity is null or passenger_capacity > 0),
  constraint aircraft_dimensions_positive
    check (
      (wingspan_ft    is null or wingspan_ft    > 0) and
      (length_ft      is null or length_ft      > 0) and
      (tail_height_ft is null or tail_height_ft > 0) and
      (mtow_lbs       is null or mtow_lbs       > 0)
    )
);

create unique index aircraft_tail_number_key on aircraft (tail_number);
create index aircraft_tail_trgm_idx on aircraft using gin (tail_number gin_trgm_ops);
create index aircraft_model_trgm_idx on aircraft using gin (model gin_trgm_ops);

create trigger aircraft_touch
  before update on aircraft
  for each row execute function apron_touch_updated_at();
